### ISSUE TITLE
Groupby - entries with no grouped items not returned.

### ISSUE THREAD

**Issue by paulcripps** [nathanpitman/group_by.ext.ee_addon#2]
`{exp:channel:entries channel="advertising" search:ad_placement_categories="{segment_2}"  groupby="field_id_21" dynamic="no"}`

We're currently using the group by option, on the whole this works. We also search for the related categories (search:ad_placement_categories).

I've noticed that in cases where the playa field (field_id_21) is empty, the entry in question is never returned.

Removing `groupby="field_id_21"` fixed the issue, but the entries are no longer grouped.

**Comment by nathanpitman** [comment]
Paul, how would you suggest something be grouped if there is no value to group by? ;)

**Comment by paulcripps** [comment]
Good point. More coffee.
